---

kind: template
apiVersion: v1
labels:
  app: jenkins-docker-slave
  template: jenkins-docker-slave
metadata:

objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      source:
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        sourceSecret:
          name: ${SOURCE_SECRET_NAME}
      output:
        to:
          kind: ImageStreamTag
          name: jenkins-docker-slave:latest
      strategy:
        dockerStrategy:
          dockerfilePath: ./Dockerfile
      trigger:
        - type: "ConfigChange"
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: jenkins-docker-slave

parameters:
  - name: NAME
    displayName: Application name
    description: application name
    value: jenkins-docker-slave
    required: true
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    required: true
    value: https://github.tk-online.net/web/openshift.git
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you
      are not using the default branch.
    value: master
  - name: SOURCE_SECRET_NAME
    displayName: Sourcesecret Name
    required: true
    value: tobiasgit
