---
kind: Template
apiVersion: v1
labels:
  app: jenkins-docker-slave
  template: jenkins-docker-slave
metadata:
  name: jenkins-docker-slave

objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      source:
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        # sourceSecret:
        #   name: ${SOURCE_SECRET_NAME}
      output:
        to:
          kind: ImageStreamTag
          name: jenkins-docker-slave:latest
      strategy:
        dockerStrategy:
          dockerfilePath: ./Dockerfile
      trigger:
        - type: "ConfigChange"
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: jenkins-docker-slave
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        name: ${NAME}
      template:
        metadata:
          labels:
            name: ${NAME}
          name: ${NAME}
      spec:
        containers:
          - name: ${NAME}
            ports:
              - containerPort: 8080
            livenessProbe:
              timeoutSeconds: 3
              initialDelaySeconds: 30
              httpGet:
                path: "/"
                port: 8080
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - jenkins-docker-slave
            from:
              kind: "ImageStreamTag"
              name: "jenkins-docker-slave:latest"
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      ports:
        - name: app
          port: 8080
          targetPort: 8080
      selector:
        name: ${NAME}

parameters:
  - name: NAME
    displayName: Application name
    description: application name
    value: jenkins-docker-slave
    required: true
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    required: true
    value: git@github.com:Madomur/openshift-jenkins-docker-slave.git
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you
      are not using the default branch.
    value: master
  - name: SOURCE_SECRET_NAME
    displayName: Sourcesecret Name
    required: true
    value: tobiasgit
